// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// subimmer_sample_prob_index
Rcpp::NumericVector subimmer_sample_prob_index(Rcpp::NumericMatrix probs, Rcpp::NumericVector rn);
RcppExport SEXP immer_subimmer_sample_prob_index(SEXP probsSEXP, SEXP rnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rn(rnSEXP);
    rcpp_result_gen = Rcpp::wrap(subimmer_sample_prob_index(probs, rn));
    return rcpp_result_gen;
END_RCPP
}
// subimmer_probs_gpcm_rcpp
Rcpp::NumericVector subimmer_probs_gpcm_rcpp(Rcpp::NumericVector x, Rcpp::NumericVector theta, Rcpp::NumericVector b, Rcpp::NumericVector a, int K, Rcpp::NumericVector x_ind);
RcppExport SEXP immer_subimmer_probs_gpcm_rcpp(SEXP xSEXP, SEXP thetaSEXP, SEXP bSEXP, SEXP aSEXP, SEXP KSEXP, SEXP x_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_ind(x_indSEXP);
    rcpp_result_gen = Rcpp::wrap(subimmer_probs_gpcm_rcpp(x, theta, b, a, K, x_ind));
    return rcpp_result_gen;
END_RCPP
}
// subimmer_probs_hrm_rcpp
Rcpp::NumericVector subimmer_probs_hrm_rcpp(Rcpp::NumericVector x, Rcpp::NumericVector xi, Rcpp::NumericVector phi, Rcpp::NumericVector psi, int K, Rcpp::NumericVector x_ind);
RcppExport SEXP immer_subimmer_probs_hrm_rcpp(SEXP xSEXP, SEXP xiSEXP, SEXP phiSEXP, SEXP psiSEXP, SEXP KSEXP, SEXP x_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_ind(x_indSEXP);
    rcpp_result_gen = Rcpp::wrap(subimmer_probs_hrm_rcpp(x, xi, phi, psi, K, x_ind));
    return rcpp_result_gen;
END_RCPP
}
// subimmer_probs_gpcm_testlet_rcpp
Rcpp::NumericVector subimmer_probs_gpcm_testlet_rcpp(Rcpp::NumericVector x, Rcpp::NumericVector theta, Rcpp::NumericVector u, Rcpp::NumericVector b, Rcpp::NumericVector a, int K, Rcpp::NumericVector x_ind);
RcppExport SEXP immer_subimmer_probs_gpcm_testlet_rcpp(SEXP xSEXP, SEXP thetaSEXP, SEXP uSEXP, SEXP bSEXP, SEXP aSEXP, SEXP KSEXP, SEXP x_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_ind(x_indSEXP);
    rcpp_result_gen = Rcpp::wrap(subimmer_probs_gpcm_testlet_rcpp(x, theta, u, b, a, K, x_ind));
    return rcpp_result_gen;
END_RCPP
}
// immer_sampling_xi
Rcpp::NumericVector immer_sampling_xi(Rcpp::NumericVector x, Rcpp::NumericVector theta, Rcpp::NumericVector b, Rcpp::NumericVector a, int K, Rcpp::NumericVector x_ind, Rcpp::NumericVector phi, Rcpp::NumericVector psi, double eps, Rcpp::NumericVector pid, Rcpp::NumericVector rater, int N);
RcppExport SEXP immer_immer_sampling_xi(SEXP xSEXP, SEXP thetaSEXP, SEXP bSEXP, SEXP aSEXP, SEXP KSEXP, SEXP x_indSEXP, SEXP phiSEXP, SEXP psiSEXP, SEXP epsSEXP, SEXP pidSEXP, SEXP raterSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_ind(x_indSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pid(pidSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rater(raterSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(immer_sampling_xi(x, theta, b, a, K, x_ind, phi, psi, eps, pid, rater, N));
    return rcpp_result_gen;
END_RCPP
}
// probs_gpcm_rcpp
Rcpp::NumericVector probs_gpcm_rcpp(Rcpp::NumericVector x, Rcpp::NumericVector theta, Rcpp::NumericVector b, Rcpp::NumericVector a, int K, Rcpp::NumericVector x_ind);
RcppExport SEXP immer_probs_gpcm_rcpp(SEXP xSEXP, SEXP thetaSEXP, SEXP bSEXP, SEXP aSEXP, SEXP KSEXP, SEXP x_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_ind(x_indSEXP);
    rcpp_result_gen = Rcpp::wrap(probs_gpcm_rcpp(x, theta, b, a, K, x_ind));
    return rcpp_result_gen;
END_RCPP
}
// probs_hrm_rcpp
Rcpp::NumericVector probs_hrm_rcpp(Rcpp::NumericVector x, Rcpp::NumericVector xi, Rcpp::NumericVector phi, Rcpp::NumericVector psi, int K, Rcpp::NumericVector x_ind);
RcppExport SEXP immer_probs_hrm_rcpp(SEXP xSEXP, SEXP xiSEXP, SEXP phiSEXP, SEXP psiSEXP, SEXP KSEXP, SEXP x_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_ind(x_indSEXP);
    rcpp_result_gen = Rcpp::wrap(probs_hrm_rcpp(x, xi, phi, psi, K, x_ind));
    return rcpp_result_gen;
END_RCPP
}
// sample_prob_index
Rcpp::NumericVector sample_prob_index(Rcpp::NumericMatrix probs, Rcpp::NumericVector rn);
RcppExport SEXP immer_sample_prob_index(SEXP probsSEXP, SEXP rnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rn(rnSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_prob_index(probs, rn));
    return rcpp_result_gen;
END_RCPP
}
// probs_gpcm_testlet_rcpp
Rcpp::NumericVector probs_gpcm_testlet_rcpp(Rcpp::NumericVector x, Rcpp::NumericVector theta, Rcpp::NumericVector u, Rcpp::NumericVector b, Rcpp::NumericVector a, int K, Rcpp::NumericVector x_ind);
RcppExport SEXP immer_probs_gpcm_testlet_rcpp(SEXP xSEXP, SEXP thetaSEXP, SEXP uSEXP, SEXP bSEXP, SEXP aSEXP, SEXP KSEXP, SEXP x_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_ind(x_indSEXP);
    rcpp_result_gen = Rcpp::wrap(probs_gpcm_testlet_rcpp(x, theta, u, b, a, K, x_ind));
    return rcpp_result_gen;
END_RCPP
}
