## File Name: RcppExports.R
## File Version: 0.09
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subimmer_sample_prob_index <- function(probs, rn) {
    .Call('_immer_subimmer_sample_prob_index', PACKAGE = 'immer', probs, rn)
}

subimmer_probs_gpcm_rcpp <- function(x, theta, b, a, K, x_ind) {
    .Call('_immer_subimmer_probs_gpcm_rcpp', PACKAGE = 'immer', x, theta, b, a, K, x_ind)
}

subimmer_probs_hrm_rcpp <- function(x, xi, phi, psi, K, x_ind) {
    .Call('_immer_subimmer_probs_hrm_rcpp', PACKAGE = 'immer', x, xi, phi, psi, K, x_ind)
}

subimmer_probs_gpcm_testlet_rcpp <- function(x, theta, u, b, a, K, x_ind) {
    .Call('_immer_subimmer_probs_gpcm_testlet_rcpp', PACKAGE = 'immer', x, theta, u, b, a, K, x_ind)
}

immer_sampling_xi <- function(x, theta, b, a, K, x_ind, phi, psi, eps, pid, rater, N) {
    .Call('_immer_immer_sampling_xi', PACKAGE = 'immer', x, theta, b, a, K, x_ind, phi, psi, eps, pid, rater, N)
}

probs_gpcm_rcpp <- function(x, theta, b, a, K, x_ind) {
    .Call('_immer_probs_gpcm_rcpp', PACKAGE = 'immer', x, theta, b, a, K, x_ind)
}

probs_hrm_rcpp <- function(x, xi, phi, psi, K, x_ind) {
    .Call('_immer_probs_hrm_rcpp', PACKAGE = 'immer', x, xi, phi, psi, K, x_ind)
}

sample_prob_index <- function(probs, rn) {
    .Call('_immer_sample_prob_index', PACKAGE = 'immer', probs, rn)
}

probs_gpcm_testlet_rcpp <- function(x, theta, u, b, a, K, x_ind) {
    .Call('_immer_probs_gpcm_testlet_rcpp', PACKAGE = 'immer', x, theta, u, b, a, K, x_ind)
}

immer_ccml_proc_freq_item_pair <- function(dat, dat_resp, K, weights, ii, jj) {
    .Call('_immer_immer_ccml_proc_freq_item_pair', PACKAGE = 'immer', dat, dat_resp, K, weights, ii, jj)
}

immer_ccml_proc_freq <- function(dat, dat_resp, K, weights) {
    .Call('_immer_immer_ccml_proc_freq', PACKAGE = 'immer', dat, dat_resp, K, weights)
}

immer_ccml_calc_item_intercepts <- function(b_fixed, A_, par) {
    .Call('_immer_immer_ccml_calc_item_intercepts', PACKAGE = 'immer', b_fixed, A_, par)
}

immer_ccml_probs <- function(b, ll_index1, item10, item20, cat1, cat2, max_ll_index) {
    .Call('_immer_immer_ccml_probs', PACKAGE = 'immer', b, ll_index1, item10, item20, cat1, cat2, max_ll_index)
}

immer_ccml_probs_from_par <- function(b_fixed, A_, par, ll_index1, item10, item20, cat1, cat2, max_ll_index, pp1, pp2, h1, h2) {
    .Call('_immer_immer_ccml_probs_from_par', PACKAGE = 'immer', b_fixed, A_, par, ll_index1, item10, item20, cat1, cat2, max_ll_index, pp1, pp2, h1, h2)
}

immer_ccml_opt_function <- function(b, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index) {
    .Call('_immer_immer_ccml_opt_function', PACKAGE = 'immer', b, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index)
}

immer_ccml_opt_function_par <- function(b_fixed, A_, par, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index) {
    .Call('_immer_immer_ccml_opt_function_par', PACKAGE = 'immer', b_fixed, A_, par, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index)
}

immer_ccml_gradient <- function(b, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index) {
    .Call('_immer_immer_ccml_gradient', PACKAGE = 'immer', b, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index)
}

immer_ccml_gradient_par <- function(b_fixed, A_, par, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index) {
    .Call('_immer_immer_ccml_gradient_par', PACKAGE = 'immer', b_fixed, A_, par, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index)
}

immer_ccml_se <- function(b_fixed, A_, par, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index, h) {
    .Call('_immer_immer_ccml_se', PACKAGE = 'immer', b_fixed, A_, par, ll_index1, item10, item20, cat1, cat2, n, ntot, max_ll_index, h)
}

immer_gpcm_prob_one_item_one_person <- function(theta1, b_ii, a) {
    .Call('_immer_immer_gpcm_prob_one_item_one_person', PACKAGE = 'immer', theta1, b_ii, a)
}

immer_gpcm_calc_probs <- function(theta, b, a) {
    .Call('_immer_immer_gpcm_calc_probs', PACKAGE = 'immer', theta, b, a)
}

immer_irt_likelihood_gpcm <- function(probs, dat, dat_resp, TP, K) {
    .Call('_immer_immer_irt_likelihood_gpcm', PACKAGE = 'immer', probs, dat, dat_resp, TP, K)
}

immer_latent_regression_prior_normal <- function(mu, sigma, theta) {
    .Call('_immer_immer_latent_regression_prior_normal', PACKAGE = 'immer', mu, sigma, theta)
}

immer_latent_regression_posterior <- function(like, prior, weights) {
    .Call('_immer_immer_latent_regression_posterior', PACKAGE = 'immer', like, prior, weights)
}

immer_latent_regression_calc_mu_sigma <- function(X, group, G, beta, gamma) {
    .Call('_immer_immer_latent_regression_calc_mu_sigma', PACKAGE = 'immer', X, group, G, beta, gamma)
}

immer_add_elements <- function(x, pos, h) {
    .Call('_immer_immer_add_elements', PACKAGE = 'immer', x, pos, h)
}

immer_latent_regression_calc_individual_likelihood <- function(X, group, G, pars, theta, weights, like) {
    .Call('_immer_immer_latent_regression_calc_individual_likelihood', PACKAGE = 'immer', X, group, G, pars, theta, weights, like)
}

immer_latent_regression_calc_individual_likelihood_increment <- function(X, group, G, pars, theta, weights, like, pos1, h1, pos2, h2) {
    .Call('_immer_immer_latent_regression_calc_individual_likelihood_increment', PACKAGE = 'immer', X, group, G, pars, theta, weights, like, pos1, h1, pos2, h2)
}

immer_latent_regression_vcov_xpd <- function(X, group, G, pars, theta, weights, like, h) {
    .Call('_immer_immer_latent_regression_vcov_xpd', PACKAGE = 'immer', X, group, G, pars, theta, weights, like, h)
}

immer_jml_prob_one_item_one_person <- function(theta1, b_ii) {
    .Call('_immer_immer_jml_prob_one_item_one_person', PACKAGE = 'immer', theta1, b_ii)
}

immer_trim_increment_rcpp <- function(incr, max_incr) {
    .Call('_immer_immer_trim_increment_rcpp', PACKAGE = 'immer', incr, max_incr)
}

immer_abs2 <- function(x) {
    .Call('_immer_immer_abs2', PACKAGE = 'immer', x)
}

immer_jml_update_item_derivatives <- function(theta, score_items, N, K, I, dat_resp, b, A_, xsi, max_incr, b_fixed, ItemScore, update, update_weights) {
    .Call('_immer_immer_jml_update_item_derivatives', PACKAGE = 'immer', theta, score_items, N, K, I, dat_resp, b, A_, xsi, max_incr, b_fixed, ItemScore, update, update_weights)
}

immer_jml_update_theta_derivatives <- function(theta, score_pers, N, K, I, b, max_incr, dat_resp, update) {
    .Call('_immer_immer_jml_update_theta_derivatives', PACKAGE = 'immer', theta, score_pers, N, K, I, b, max_incr, dat_resp, update)
}

