## File Name: RcppExports.R
## File Version: 0.06
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subimmer_sample_prob_index <- function(probs, rn) {
    .Call('_immer_subimmer_sample_prob_index', PACKAGE = 'immer', probs, rn)
}

subimmer_probs_gpcm_rcpp <- function(x, theta, b, a, K, x_ind) {
    .Call('_immer_subimmer_probs_gpcm_rcpp', PACKAGE = 'immer', x, theta, b, a, K, x_ind)
}

subimmer_probs_hrm_rcpp <- function(x, xi, phi, psi, K, x_ind) {
    .Call('_immer_subimmer_probs_hrm_rcpp', PACKAGE = 'immer', x, xi, phi, psi, K, x_ind)
}

subimmer_probs_gpcm_testlet_rcpp <- function(x, theta, u, b, a, K, x_ind) {
    .Call('_immer_subimmer_probs_gpcm_testlet_rcpp', PACKAGE = 'immer', x, theta, u, b, a, K, x_ind)
}

immer_sampling_xi <- function(x, theta, b, a, K, x_ind, phi, psi, eps, pid, rater, N) {
    .Call('_immer_immer_sampling_xi', PACKAGE = 'immer', x, theta, b, a, K, x_ind, phi, psi, eps, pid, rater, N)
}

probs_gpcm_rcpp <- function(x, theta, b, a, K, x_ind) {
    .Call('_immer_probs_gpcm_rcpp', PACKAGE = 'immer', x, theta, b, a, K, x_ind)
}

probs_hrm_rcpp <- function(x, xi, phi, psi, K, x_ind) {
    .Call('_immer_probs_hrm_rcpp', PACKAGE = 'immer', x, xi, phi, psi, K, x_ind)
}

sample_prob_index <- function(probs, rn) {
    .Call('_immer_sample_prob_index', PACKAGE = 'immer', probs, rn)
}

probs_gpcm_testlet_rcpp <- function(x, theta, u, b, a, K, x_ind) {
    .Call('_immer_probs_gpcm_testlet_rcpp', PACKAGE = 'immer', x, theta, u, b, a, K, x_ind)
}

immer_jml_prob_one_item_one_person <- function(theta1, b_ii) {
    .Call('_immer_immer_jml_prob_one_item_one_person', PACKAGE = 'immer', theta1, b_ii)
}

immer_trim_increment_rcpp <- function(incr, max_incr) {
    .Call('_immer_immer_trim_increment_rcpp', PACKAGE = 'immer', incr, max_incr)
}

immer_abs2 <- function(x) {
    .Call('_immer_immer_abs2', PACKAGE = 'immer', x)
}

immer_jml_update_item_derivatives <- function(theta, score_items, N, K, I, dat_resp, b, A_, xsi, max_incr, b_fixed, ItemScore, update, update_weights) {
    .Call('_immer_immer_jml_update_item_derivatives', PACKAGE = 'immer', theta, score_items, N, K, I, dat_resp, b, A_, xsi, max_incr, b_fixed, ItemScore, update, update_weights)
}

immer_jml_update_theta_derivatives <- function(theta, score_pers, N, K, I, b, max_incr, dat_resp, update) {
    .Call('_immer_immer_jml_update_theta_derivatives', PACKAGE = 'immer', theta, score_pers, N, K, I, b, max_incr, dat_resp, update)
}

