# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subimmer_sample_prob_index <- function(probs, rn) {
    .Call('immer_subimmer_sample_prob_index', PACKAGE = 'immer', probs, rn)
}

subimmer_probs_gpcm_rcpp <- function(x, theta, b, a, K, x_ind) {
    .Call('immer_subimmer_probs_gpcm_rcpp', PACKAGE = 'immer', x, theta, b, a, K, x_ind)
}

subimmer_probs_hrm_rcpp <- function(x, xi, phi, psi, K, x_ind) {
    .Call('immer_subimmer_probs_hrm_rcpp', PACKAGE = 'immer', x, xi, phi, psi, K, x_ind)
}

subimmer_probs_gpcm_testlet_rcpp <- function(x, theta, u, b, a, K, x_ind) {
    .Call('immer_subimmer_probs_gpcm_testlet_rcpp', PACKAGE = 'immer', x, theta, u, b, a, K, x_ind)
}

immer_sampling_xi <- function(x, theta, b, a, K, x_ind, phi, psi, eps, pid, rater, N) {
    .Call('immer_immer_sampling_xi', PACKAGE = 'immer', x, theta, b, a, K, x_ind, phi, psi, eps, pid, rater, N)
}

probs_gpcm_rcpp <- function(x, theta, b, a, K, x_ind) {
    .Call('immer_probs_gpcm_rcpp', PACKAGE = 'immer', x, theta, b, a, K, x_ind)
}

probs_hrm_rcpp <- function(x, xi, phi, psi, K, x_ind) {
    .Call('immer_probs_hrm_rcpp', PACKAGE = 'immer', x, xi, phi, psi, K, x_ind)
}

sample_prob_index <- function(probs, rn) {
    .Call('immer_sample_prob_index', PACKAGE = 'immer', probs, rn)
}

probs_gpcm_testlet_rcpp <- function(x, theta, u, b, a, K, x_ind) {
    .Call('immer_probs_gpcm_testlet_rcpp', PACKAGE = 'immer', x, theta, u, b, a, K, x_ind)
}

